name: longread_env

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - snakemake-minimal
  - fastqc
  - nanoplot
  - biopython
  - pandas
  - matplotlib
  - seaborn
  - pip
  - pip:
      - plotly
      - kaleido
